# Generated by Django 4.2 on 2023-04-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, upload_to='calendar/')),
                ('alt', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=100)),
                ('plan_img', models.ImageField(upload_to='plans/')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=150)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majorsweb.major')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majorsweb.subjects_category')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majorsweb.major')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majorsweb.subject')),
            ],
        ),
    ]
