# Generated by Django 4.2 on 2023-04-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0002_rename_subject_resource_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects_category',
            name='major',
        ),
    ]
