# Generated by Django 4.2 on 2023-04-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0005_alter_subject_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='major',
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject', to='majorsweb.major'),
        ),
    ]
