# Generated by Django 4.2 on 2023-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0006_remove_subject_major_subject_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='major',
            field=models.ManyToManyField(blank=True, related_name='subject', to='majorsweb.major'),
        ),
    ]
