# Generated by Django 4.2 on 2023-04-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0007_alter_subject_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
