# Generated by Django 4.2 on 2023-04-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0010_alter_resource_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
