# Generated by Django 4.2 on 2023-05-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0011_major_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='second_plan_img',
            field=models.ImageField(blank=True, upload_to='plans/'),
        ),
    ]
