# Generated by Django 4.2 on 2023-05-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0012_major_second_plan_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='face_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='tele_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
