# Generated by Django 4.2 on 2023-05-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0013_team_description_team_face_link_team_tele_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bot_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='website_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
