# Generated by Django 4.2 on 2023-07-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0018_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sec_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
