# Generated by Django 4.2 on 2024-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0019_subject_sec_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='insta_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
