# Generated by Django 4.2 on 2024-05-12 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0021_alter_team_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='logo',
        ),
        migrations.AddField(
            model_name='major',
            name='darkLogo',
            field=models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
        migrations.AddField(
            model_name='major',
            name='lightLogo',
            field=models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
    ]
