# Generated by Django 4.2 on 2024-05-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0022_remove_major_logo_major_darklogo_major_lightlogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('office', models.CharField(blank=True, max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majorsweb.department')),
            ],
        ),
    ]
