# Generated by Django 4.2 on 2024-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0024_team_union_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='union_logo',
        ),
        migrations.AddField(
            model_name='team',
            name='union_light_logo',
            field=models.ImageField(blank=True, upload_to='unions/logo/light/'),
        ),
        migrations.AddField(
            model_name='team',
            name='union_logo_dark',
            field=models.ImageField(blank=True, upload_to='unions/logo/dark'),
        ),
    ]
