# Generated by Django 4.2 on 2024-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0027_subjects_category_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects_category',
            name='hours',
        ),
        migrations.AddField(
            model_name='subject',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
