# Generated by Django 4.2 on 2024-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorsweb', '0028_remove_subjects_category_hours_subject_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
